#ifndef GAME_CLIENT_COMPONENTS_CHILLERBOT_VERSION_H
#define GAME_CLIENT_COMPONENTS_CHILLERBOT_VERSION_H

#define CHILLERBOT_BUILD_DATE __DATE__ ", " __TIME__
#define CHILLERBOT_VERSIONNR 9
#define CHILLERBOT_VERSION "0.0.9"

#define CYBERCRACK_VERSIONNR 1
#define CYBERCRACK_VERSION "1.0"

#endif
